name: .NET
on:
  push:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test Cosette.Polyglot.Tests
      run: dotnet test Cosette.Polyglot.Tests --no-build --verbosity normal
    - name: Test Cosette.Tests
      run: dotnet test Cosette.Tests --no-build --verbosity normal